### ISSUE TITLE
PowerCLI 12.1 Set-Datacenter cmdlet fails when it is called in SRS runspace

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#13] opened 2020-10-28 20:26 UTC
When I run a multi-line script like this
```
New-Datacenter -Name TestDC -Location (Get-Folder -Name datacenters)
Get-Datacenter -Name TestDC | Set-Datacenter -Name TestDC-New -Confirm:$false
Get-Datacenter -Name TestDC-New | Remove-Datacenter -Confirm:$false
```
the output from the New-Datacenter cmdlet is returned.
The output of the Set-Datacenter cmdlet is apparently not returned.
Via the Web Client I see that all code is executed though.

This also explains why the '_Runs CRUD10Datacenters PowerCLI Script_' Pester test fails.
The 2nd part, the output of the renames of the datacenters doesn't show in the script output.

**Comment by dmilov** [comment] 2020-11-02 08:14
It turns out we are hitting PowerCLI 12.1 bug here. The Set-Datacenter cmdlet throws the below error

 Set-Datacenter          com.vmware.vapi.std.errors.unauthenticated {'messages': [com.vmware.vapi.std.localizable_message {'id': com.vmware.vapi.endpoint.method.authentication.required, 'default_message': Authentication required., 'args': [], 'params': , 'localized':}], 'data': , 'error_type': UNAUTHENT

recorded in the error streams of the test script.

@lucdekens Is your SRS instance packaged with PowerCLI 12.1?

**Comment by lucdekens** [comment] 2020-11-02 08:20
Yes, it is.
Should I use 12.0?

**Comment by dmilov** [comment] 2020-11-02 08:23
12.1 should be good, but this bug was a surprise for me as well. I'll do further investigation. If it is a blocker for you, you can switch to 12.0.

**Comment by lucdekens** [comment] 2020-11-02 08:26
Not really, I just noticed it because it was included in the Pester test.

**Comment by dmilov** [comment] 2020-11-02 08:37
It is bad combination of good intentions, PowerCLI 12.1 introduces this regression in its task wait core functionality. If Connect-VIServer by username and password is used, this bug is not reproducible. Connect-VIServer -SamlSecurityContext though, which is used by SRS, reproduces this one.

**Comment by lucdekens** [comment] 2020-11-02 08:48
That is indeed a fringe case :-)

**Comment by dmilov** [comment] 2020-11-02 13:37
Bug reported to PowerCLI product. This bug will have impact on SRS release. If PowerCLI with fix is not available before SRS first release, SRS will be bundled with PowerCLI 12.0.

**Comment by dmilov** [comment] 2020-11-02 16:37
Fix merged into master

**Closed by dmilov** 2020-11-02 16:37 UTC
Labels: bug
